# 넘파이 30분내로 정리하기 

In [1]:
import numpy as np

In [2]:
a = np.arange(21)

In [3]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [5]:
b = a.reshape(3,7)

In [6]:
b

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20]])

In [7]:
a.shape

(21,)

In [8]:
b.shape

(3, 7)

In [9]:
a.ndim

1

In [10]:
b.ndim

2

In [11]:
a.dtype.name

'int64'

In [12]:
type(a)

numpy.ndarray

In [16]:
a = np.random.randint(0,2,size=(48,366,3))
print(a)
b = np.delete(a,np.s_[-1:],1)
print(b.shape) # <--- (48,365,3)

[[[0 1 0]
  [0 0 0]
  [1 0 0]
  ...
  [0 1 1]
  [0 1 0]
  [1 1 1]]

 [[1 0 0]
  [1 1 0]
  [1 0 1]
  ...
  [1 1 1]
  [1 1 0]
  [1 0 0]]

 [[0 0 1]
  [0 0 1]
  [0 1 1]
  ...
  [0 1 0]
  [0 1 1]
  [0 0 0]]

 ...

 [[0 0 1]
  [0 1 0]
  [0 1 1]
  ...
  [1 1 0]
  [0 0 1]
  [1 1 1]]

 [[1 1 1]
  [1 0 0]
  [1 1 0]
  ...
  [1 0 1]
  [0 1 1]
  [0 0 1]]

 [[1 1 1]
  [0 0 0]
  [0 1 0]
  ...
  [1 0 0]
  [0 0 1]
  [1 0 1]]]
(48, 365, 3)
